[project]
name = "dfq_vla"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "apollo-torch>=1.0.3",
    "datasets>=4.4.2",
    "evaluate>=0.4.6",
    "flash-attn",
    "liger-kernel>=0.6.4",
    "matplotlib>=3.10.8",
    "peft>=0.18.0",
    "pillow-simd>=9.5.0.post2",
    "pycocoevalcap>=1.2",
    "pyyaml>=6.0.3",
    "tensorboard>=2.20.0",
    "timm>=1.0.22",
    "torchvision>=0.24.1",
    "trackio>=0.13.1",
    "transformers==4.57.3",
    "trl==0.15",
]

[tool.uv.sources]
flash-attn = { path = "flash_attn-2.8.3+cu12torch2.5cxx11abiFALSE-cp310-cp310-linux_x86_64.whl" }
